name: Cross-Platform Electron Build

on:
  push:
    tags:
      - 'v*.*.*'   # Trigger only when version tag like v1.0.0 is pushed
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-windows:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build React
        run: npm run build

      - name: Package Windows
        run: npm run dist -- --win

  build-linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '20'

      - name: Prepare build tools
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Install dependencies
        run: npm ci

      - name: Build React
        run: npm run build

      - name: Package Linux
        run: npm run dist -- --linux

  build-mac:
    name: macOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build React
        run: npm run build

      - name: Package macOS
        run: npm run dist -- --mac
